### ISSUE TITLE
the day parameter to display.

### ISSUE THREAD

**Issue by snipeTR** [51FuR4nk/wallet-monitor#2]
A parameter must be added. --day-range N
It should be set to display as many days as N written. only for those who want to see more than 7 days chart. eg: 14 days, or 30 days.

**Comment by 51FuR4nk** [comment]
done, please checkout the last version.
In case the day-range exceed the history it will be capped to the chain beginning

**Comment by snipeTR** [comment]
Tnx, you are best.
