### ISSUE TITLE
refresh bug

### ISSUE THREAD

**Issue by snipeTR** [51FuR4nk/wallet-monitor#3]
up new code, low old code
two apps opened at the same time
![image](https://user-images.githubusercontent.com/31975916/161237659-05e08d49-a156-4d33-a69e-fbdc493d574b.png)

**Comment by 51FuR4nk** [comment]
I did,t get what the problem is

**Comment by 51FuR4nk** [comment]
could it be that you run the script as soon the wallet rpc server started?
the wallet rpc need some time for retrieve the data and if you query it too son it will give you partial data

**Comment by snipeTR** [comment]
20 sec timeout.
I will more test.
