### ISSUE TITLE
please add beep

### ISSUE THREAD

**Issue by snipeTR** [51FuR4nk/wallet-monitor#4]
hi can you add --beep command. When the reward or coin comes, it will beep. the more dero comes, the longer it beeps. 
(example: 1 dero 100ms, 0.0615 dero 50ms. min 50 ms max 1000 ms)

also can you update the readme file it still shows old stuff. 
Also, can you put the python package download command to install the necessary packages. 
People who don't know python can't use it.

**Comment by 51FuR4nk** [comment]
I like the beep functionality!
And yes I should update the readme...

I hope to find some time in the next days

**Comment by snipeTR** [comment]
I have a few more ideas, if you want I can offer them.

**Comment by 51FuR4nk** [comment]
for the moment I used "beepy" library. Is not possible to configure the sound time but should be cross platform.
Since I test only on linux please let me know if there is any problem.
Remember to use --sound option

If you have more suggestion please let me know.
